#!/usr/bin/env bash
# Configures a server and a default header response
apt update
header_name="X-served-By"
hostname=$(hostname)
apt install nginx -y
service nginx start
echo "Hello world" > /var/www/html/index.html
sed -i "/http {/a \    add_header $header_name $hostname;" /etc/nginx/nginx.conf
service nginx restart
