#!/usr/bin/env bash
# Displays 12 hours and 59 minutes of the clock
i=0
while [ $i -le 12 ]
do
    j=1
    echo "Hour: $i"
    while [ $j -le 59 ]
    do
	echo $j
	(( j += 1 ))
    done
    (( i += 1 ))
done
